name: free-pascal-application-util-packages-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build and tests
        run: |
          docker run -v "$(pwd)":/root/app/ -v "$(pwd)"/target:/root/app/target/ -i ghcr.io/bogomolov-a-a/free-pascal-with-lazbuild-trunk:latest ls -a
        
